#!/usr/bin/env python3
"""workpaper-kit: shared proof-backed workpaper/proof-packet engine.

Canonical source of truth. Edit this file only. The byte-identical
``scripts/_workpaper.py`` copies vendored inside each skill are generated by
``workpaper-kit/sync.sh`` and must never be hand-edited.

The kit owns the downstream workpaper machine that ``get-yearly-fx-rate`` and
``get-year-end-fx-rate`` share once a rate has already been determined: the
proof-file copy + SHA-256 packet schema, the folder naming and overwrite
guard, the ``workpaper.md`` / ``workpaper.json`` writers, the PDF engine, and
the cited-answer helpers. The kit never fetches, never parses a rate, and
never touches currency aliases or source layers - a caller hands it an
already-parsed :class:`~decimal.Decimal` plus a :class:`WorkpaperSpec` and the
kit writes ``workpaper.md`` + ``workpaper.json`` + ``workpaper.pdf`` and a
copied, hashed source proof under ``work/<slug>/``.

All divergence between the two skills is absorbed by ``WorkpaperSpec`` fields
(document title/subtitle, rate phrase, caveats, extra rows, extra JSON, proof
policy). The PDF engine is yearly's, generalized; year-end adopts its look.
"""

from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import sys
import unicodedata
from dataclasses import dataclass
from decimal import Decimal, localcontext
from pathlib import Path
from typing import Iterable, Sequence

# Reciprocal division and quantization run inside a fixed-precision context so
# output never depends on the caller's ambient decimal context.
_DECIMAL_PREC = 28


class RateError(Exception):
    """User-correctable error, carrying a process exit code.

    Shared with the skills so a ``build_workpaper`` failure is caught by the
    same ``except RateError`` the skills already use.
    """

    def __init__(self, message: str, code: int = 1):
        super().__init__(message)
        self.code = code


# --------------------------------------------------------------------------- #
# Small domain-agnostic helpers (moved verbatim from the yearly reference).    #
# --------------------------------------------------------------------------- #


def clean_text(value: object) -> str:
    return re.sub(r"\s+", " ", str(value if value is not None else "")).strip()


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "source"


def fmt_decimal(value: Decimal, max_places: int = 12) -> str:
    text = format(value, "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    if "." in text and len(text.split(".", 1)[1]) > max_places:
        with localcontext() as ctx:
            ctx.prec = _DECIMAL_PREC
            quant = Decimal("1").scaleb(-max_places)
            text = format(value.quantize(quant), "f").rstrip("0").rstrip(".")
    return text


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def as_abs(path: Path) -> str:
    return str(path.resolve())


def build_rate_values(rate: Decimal, direction: str) -> tuple[Decimal, Decimal]:
    """Return ``(foreign_per_usd, usd_per_foreign)`` for a positive rate.

    The kit computes the reciprocal here; it never parses the rate itself.
    """
    # Guard finiteness before the ordering check: NaN <= 0 raises
    # InvalidOperation, and Infinity would slip a garbage rate through.
    if not rate.is_finite() or rate <= 0:
        raise RateError("Rate must be a finite number greater than zero.", 2)
    if direction not in ("foreign-per-usd", "usd-per-foreign"):
        raise RateError(f"Unsupported rate direction: {direction}", 2)
    with localcontext() as ctx:
        ctx.prec = _DECIMAL_PREC
        reciprocal = Decimal(1) / rate
    if direction == "foreign-per-usd":
        return rate, reciprocal
    return reciprocal, rate


# --------------------------------------------------------------------------- #
# PDF primitives (yearly's engine; year-end adopts this look).                 #
# --------------------------------------------------------------------------- #


# The PDF uses the standard-14 latin-1 fonts, so text outside latin-1 cannot be
# drawn. Rather than let it become "?", transliterate common symbols and
# punctuation to a legible latin-1 equivalent (workpaper.md / workpaper.json keep
# the original UTF-8). Anything left is decomposed (accents dropped) and only
# truly unmappable code points fall back to "?".
_PDF_TRANSLIT = {
    "€": "EUR", "₩": "KRW", "₹": "INR", "₪": "ILS",
    "₺": "TRY", "฿": "THB", "₽": "RUB", "₴": "UAH",
    "₦": "NGN", "₱": "PHP", "₫": "VND", "₡": "CRC",
    "₸": "KZT", "₾": "GEL", "₼": "AZN", "₵": "GHS",
    "‘": "'", "’": "'", "‚": ",", "“": '"', "”": '"',
    "„": '"', "–": "-", "—": "--", "―": "--", "…": "...",
    "•": "-", "−": "-", "′": "'", "″": '"', " ": " ",
    "ł": "l", "Ł": "L", "đ": "d", "Đ": "D",
}


def _to_latin1_safe(text: str) -> str:
    out: list[str] = []
    for ch in text:
        mapped = _PDF_TRANSLIT.get(ch)
        if mapped is not None:
            out.append(mapped)
            continue
        try:
            ch.encode("latin-1")
        except UnicodeEncodeError:
            stripped = "".join(
                c for c in unicodedata.normalize("NFKD", ch) if not unicodedata.combining(c)
            )
            safe = stripped.encode("latin-1", errors="ignore").decode("latin-1")
            out.append(safe if safe else "?")
        else:
            out.append(ch)
    return "".join(out)


def escape_pdf_text(value: object) -> str:
    normalized = _to_latin1_safe(clean_text(str(value)))
    return normalized.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def wrap_text(value: object, width: int = 92) -> list[str]:
    max_width = max(8, width)
    words = clean_text(str(value)).split()
    if not words:
        return [""]
    lines: list[str] = []
    current = ""
    for word in words:
        chunks = [word[index : index + max_width] for index in range(0, len(word), max_width)] or [word]
        for chunk in chunks:
            if not current:
                current = chunk
            elif len(current) + 1 + len(chunk) <= max_width:
                current += " " + chunk
            else:
                lines.append(current)
                current = chunk
    if current:
        lines.append(current)
    return lines


PDF_PAGE_WIDTH = 612
PDF_PAGE_HEIGHT = 792
PDF_MARGIN_X = 56
PDF_INNER_WIDTH = PDF_PAGE_WIDTH - (PDF_MARGIN_X * 2)
PDF_BOTTOM_MARGIN = 58
# Refined palette: a deep brand navy and a single teal accent over warm
# neutrals. Ink/muted/faint give a three-step text hierarchy; rule/wash are the
# quiet structure; brand/accent carry the color.
PDF_COLOR_INK = (0.129, 0.149, 0.196)
PDF_COLOR_MUTED = (0.435, 0.475, 0.541)
PDF_COLOR_FAINT = (0.569, 0.600, 0.655)
PDF_COLOR_RULE = (0.886, 0.906, 0.933)
PDF_COLOR_WASH = (0.965, 0.973, 0.984)
PDF_COLOR_BRAND = (0.086, 0.204, 0.373)
PDF_COLOR_BRAND_DEEP = (0.055, 0.149, 0.278)
PDF_COLOR_ACCENT = (0.106, 0.482, 0.549)
PDF_COLOR_ON_BRAND = (0.812, 0.859, 0.925)
PDF_COLOR_WHITE = (1.000, 1.000, 1.000)


def pdf_num(value: float | int) -> str:
    return f"{float(value):.2f}".rstrip("0").rstrip(".")


def pdf_color(rgb: tuple[float, float, float], operator: str) -> str:
    return f"{rgb[0]:.3f} {rgb[1]:.3f} {rgb[2]:.3f} {operator}"


def pdf_rect(
    x: float,
    y: float,
    width: float,
    height: float,
    *,
    fill: tuple[float, float, float] | None = None,
    stroke: tuple[float, float, float] | None = None,
    line_width: float = 1,
) -> str:
    commands = ["q"]
    if fill:
        commands.append(pdf_color(fill, "rg"))
    if stroke:
        commands.append(pdf_color(stroke, "RG"))
        commands.append(f"{pdf_num(line_width)} w")
    commands.append(f"{pdf_num(x)} {pdf_num(y)} {pdf_num(width)} {pdf_num(height)} re")
    if fill and stroke:
        commands.append("B")
    elif fill:
        commands.append("f")
    else:
        commands.append("S")
    commands.append("Q")
    return "\n".join(commands)


def pdf_line(
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    *,
    stroke: tuple[float, float, float] = PDF_COLOR_RULE,
    line_width: float = 0.7,
) -> str:
    return "\n".join(
        [
            "q",
            pdf_color(stroke, "RG"),
            f"{pdf_num(line_width)} w",
            f"{pdf_num(x1)} {pdf_num(y1)} m",
            f"{pdf_num(x2)} {pdf_num(y2)} l",
            "S",
            "Q",
        ]
    )


def pdf_text(
    text: object,
    x: float,
    y: float,
    *,
    font: str = "F1",
    size: float = 10,
    color: tuple[float, float, float] = PDF_COLOR_INK,
    tracking: float = 0,
) -> str:
    if text is None:
        text = ""
    return "\n".join(
        [
            "BT",
            pdf_color(color, "rg"),
            f"{pdf_num(tracking)} Tc",
            f"/{font} {pdf_num(size)} Tf",
            f"1 0 0 1 {pdf_num(x)} {pdf_num(y)} Tm",
            f"({escape_pdf_text(str(text))}) Tj",
            "ET",
        ]
    )


def wrap_for_pdf(value: object, max_width: float, font_size: float) -> list[str]:
    char_width = max(font_size * 0.52, 1)
    return wrap_text(str(value), max(12, int(max_width / char_width)))


# --------------------------------------------------------------------------- #
# Input model + presentation stash.                                            #
# --------------------------------------------------------------------------- #

# Top-level keys prefixed with this are rendering-only: readable from the
# returned workpaper dict (so ``final_text``/renderers stay pure functions of
# the dict) but stripped before ``workpaper.json`` is written, so they never
# appear in the persisted, consumer-facing JSON.
_PRESENTATION_KEY = "_presentation"

# Appended when a proof-required workpaper is built without a usable proof
# entry. Callers that require a supplied proof should validate it before
# building so no incomplete packet is created.
NO_PROOF_LIMITATION = "No saved source proof file was supplied for this manual workpaper."


@dataclass
class WorkpaperSpec:
    """Everything the kit needs to build a proof packet.

    The caller has already determined and parsed the rate; the kit computes the
    reciprocal, copies/hashes proofs, and renders md/json/pdf. All per-skill
    divergence lives in the presentation and escape-hatch fields below.
    """

    # identity / location
    output_root: str
    skill_name: str
    currency_code: str
    year: int
    # rate - kit computes the reciprocal via build_rate_values; never parses
    rate: Decimal
    rate_direction: str  # "foreign-per-usd" | "usd-per-foreign"
    # source block (common shape)
    source_title: str
    source_url: str
    source_category: str
    retrieval_date: str
    source_note: str
    # presentation (the divergence knobs)
    document_title: str  # "Yearly FX Rate Workpaper" / "Year-End FX Rate Workpaper"
    document_subtitle: str  # cover sub-line under the title
    rate_phrase: str  # "yearly average" / "year-end (2024-12-31)"
    caveats: Sequence[str]
    # escape hatches for skill-specific data
    extra_rows: Sequence[tuple[str, object]] = ()  # md + pdf key/value rows
    extra_json: dict | None = None  # deep-merged into workpaper.json
    # proof policy
    saved_proofs: Sequence[Path] = ()
    proof_required: bool = False  # False: skip missing / True: raise on missing
    proof_limitations: Sequence[str] = ()


# --------------------------------------------------------------------------- #
# PDF renderer (yearly's WorkpaperPdfRenderer, generalized).                   #
# --------------------------------------------------------------------------- #


class WorkpaperPdfRenderer:
    def __init__(self, workpaper: dict[str, object]) -> None:
        self.workpaper = workpaper
        presentation = workpaper.get(_PRESENTATION_KEY) or {}
        assert isinstance(presentation, dict)
        self.document_title = str(presentation.get("document_title", "FX Rate Workpaper"))
        self.document_subtitle = str(presentation.get("document_subtitle", ""))
        self.rate_phrase = str(presentation.get("rate_phrase", ""))
        self.extra_rows = list(presentation.get("extra_rows", ()))
        self.skill_name = str(workpaper.get("skill", ""))
        self.pages: list[list[str]] = []
        self.commands: list[str] = []
        self.y = 0.0
        self.new_page(first=True)

    def add(self, command: str) -> None:
        if command:
            self.commands.append(command)

    def new_page(self, *, first: bool = False) -> None:
        self.commands = []
        self.pages.append(self.commands)
        if first:
            self.draw_cover_header()
            self.y = 620
        else:
            self.draw_continuation_header()
            self.y = 720

    def ensure_space(self, needed: float) -> None:
        if self.y - needed < PDF_BOTTOM_MARGIN:
            self.new_page()

    def draw_cover_header(self) -> None:
        currency = self.workpaper["currency"]
        year = self.workpaper["year"]
        # Full-bleed brand band with the title reversed out in white and a
        # teal keyline along its lower edge.
        band_bottom = 658
        self.add(pdf_rect(0, band_bottom, PDF_PAGE_WIDTH, PDF_PAGE_HEIGHT - band_bottom, fill=PDF_COLOR_BRAND))
        self.add(pdf_rect(0, band_bottom, PDF_PAGE_WIDTH, 3, fill=PDF_COLOR_ACCENT))
        # status pill, upper right
        pill_w = 192
        pill_x = PDF_PAGE_WIDTH - PDF_MARGIN_X - pill_w
        self.add(pdf_rect(pill_x, 752, pill_w, 17, fill=PDF_COLOR_ACCENT))
        self.add(pdf_text("RETAINED SUPPORT WORKPAPER", pill_x + 13, 757, font="F2", size=7.5, color=PDF_COLOR_WHITE, tracking=1.1))
        # title block
        self.add(pdf_text(self.document_title, PDF_MARGIN_X, 720, font="F2", size=23, color=PDF_COLOR_WHITE))
        self.add(pdf_text(self.document_subtitle, PDF_MARGIN_X, 701, size=10, color=PDF_COLOR_ON_BRAND))
        self.add(pdf_text(f"{currency}   |   {year}", PDF_MARGIN_X, 679, font="F2", size=10.5, color=PDF_COLOR_WHITE, tracking=0.6))

    def draw_continuation_header(self) -> None:
        # slim brand ribbon carrying the document identity
        self.add(pdf_rect(0, 756, PDF_PAGE_WIDTH, PDF_PAGE_HEIGHT - 756, fill=PDF_COLOR_BRAND))
        self.add(pdf_rect(0, 756, PDF_PAGE_WIDTH, 2.5, fill=PDF_COLOR_ACCENT))
        self.add(
            pdf_text(
                f"{self.workpaper['currency']} {self.workpaper['year']} {self.document_title}",
                PDF_MARGIN_X,
                768,
                font="F2",
                size=9.5,
                color=PDF_COLOR_WHITE,
                tracking=0.3,
            )
        )
        self.add(pdf_text("PROOF PACKET", PDF_PAGE_WIDTH - PDF_MARGIN_X - 66, 768, font="F2", size=7.5, color=PDF_COLOR_ON_BRAND, tracking=1.4))

    def draw_rate_card(self) -> None:
        height = 96
        self.ensure_space(height + 22)
        top = self.y
        bottom = top - height
        pad = 24
        self.add(pdf_rect(PDF_MARGIN_X, bottom, PDF_INNER_WIDTH, height, fill=PDF_COLOR_WHITE, stroke=PDF_COLOR_RULE))
        self.add(pdf_rect(PDF_MARGIN_X, bottom, 4, height, fill=PDF_COLOR_ACCENT))
        self.add(pdf_text("EXCHANGE RATE", PDF_MARGIN_X + pad, top - 22, font="F2", size=7.5, color=PDF_COLOR_FAINT, tracking=1.6))
        self.add(
            pdf_text(
                f"1 USD = {self.workpaper['foreign_per_usd']} {self.workpaper['currency']}",
                PDF_MARGIN_X + pad,
                top - 52,
                font="F2",
                size=25,
            )
        )
        self.add(pdf_text(self.rate_phrase, PDF_MARGIN_X + pad, top - 74, size=10, color=PDF_COLOR_MUTED))
        self.add(
            pdf_text(
                f"Reciprocal: 1 {self.workpaper['currency']} = {self.workpaper['usd_per_foreign']} USD",
                PDF_MARGIN_X + pad + 246,
                top - 74,
                font="F2",
                size=9.5,
                color=PDF_COLOR_ACCENT,
            )
        )
        self.y = bottom - 28

    def draw_section_title(self, title: str) -> None:
        self.ensure_space(32)
        self.add(pdf_rect(PDF_MARGIN_X, self.y - 1.5, 2.5, 9, fill=PDF_COLOR_ACCENT))
        self.add(pdf_text(title.upper(), PDF_MARGIN_X + 11, self.y, font="F2", size=9, color=PDF_COLOR_BRAND, tracking=1.3))
        self.add(pdf_line(PDF_MARGIN_X, self.y - 9, PDF_MARGIN_X + PDF_INNER_WIDTH, self.y - 9))
        self.y -= 26

    def draw_key_value_rows(self, rows: list[tuple[str, object]], *, continuation_title: str | None = None) -> None:
        label_x = PDF_MARGIN_X
        value_x = PDF_MARGIN_X + 132
        value_width = PDF_INNER_WIDTH - 132
        for label, value in rows:
            value_lines = wrap_for_pdf(value, value_width, 9.5)
            row_height = max(22, (len(value_lines) * 12) + 10)
            if self.y - (row_height + 4) < PDF_BOTTOM_MARGIN:
                self.new_page()
                if continuation_title:
                    self.draw_section_title(f"{continuation_title} continued")
            top = self.y
            baseline = top - 14
            self.add(pdf_text(label, label_x, baseline, font="F2", size=7.5, color=PDF_COLOR_FAINT, tracking=0.3))
            for index, line in enumerate(value_lines):
                self.add(pdf_text(line, value_x, baseline - (index * 12), size=9.5, color=PDF_COLOR_INK))
            self.add(pdf_line(label_x, top - row_height, label_x + PDF_INNER_WIDTH, top - row_height, line_width=0.4))
            self.y = top - row_height
        self.y -= 18

    def draw_bullets(self, items: Iterable[object]) -> None:
        for item in items:
            lines = wrap_for_pdf(item, PDF_INNER_WIDTH - 20, 9.5)
            block_height = max(15, len(lines) * 12)
            self.ensure_space(block_height + 5)
            baseline = self.y - 9
            self.add(pdf_rect(PDF_MARGIN_X + 1, baseline - 1, 3.5, 3.5, fill=PDF_COLOR_ACCENT))
            for index, line in enumerate(lines):
                self.add(pdf_text(line, PDF_MARGIN_X + 15, baseline - (index * 12), size=9.5, color=PDF_COLOR_MUTED))
            self.y -= block_height + 6
        self.y -= 6

    def draw_footer(self) -> None:
        total = len(self.pages)
        for index, commands in enumerate(self.pages, start=1):
            commands.append(pdf_line(PDF_MARGIN_X, 44, PDF_MARGIN_X + PDF_INNER_WIDTH, 44, line_width=0.5))
            commands.append(
                pdf_text(
                    f"{self.skill_name} support workpaper | Page {index} of {total}",
                    PDF_MARGIN_X,
                    31,
                    size=7.5,
                    color=PDF_COLOR_FAINT,
                    tracking=0.2,
                )
            )

    def render(self) -> list[list[str]]:
        source = self.workpaper["source"]
        proof = self.workpaper["proof"]
        assert isinstance(source, dict)
        assert isinstance(proof, dict)
        saved_files = proof.get("saved_files", [])
        limitations = proof.get("limitations", [])
        caveats = self.workpaper.get("caveats", [])

        self.draw_rate_card()
        self.draw_section_title("Rate Details")
        rate_rows: list[tuple[str, object]] = [
            ("Currency", self.workpaper["currency"]),
            ("Year", self.workpaper["year"]),
            ("Published rate", f"{self.workpaper['rate']} ({self.workpaper['rate_direction']})"),
            ("Final display", f"1 USD = {self.workpaper['foreign_per_usd']} {self.workpaper['currency']}"),
            ("Reciprocal", f"1 {self.workpaper['currency']} = {self.workpaper['usd_per_foreign']} USD"),
        ]
        rate_rows.extend((str(label), value) for label, value in self.extra_rows)
        self.draw_key_value_rows(rate_rows, continuation_title="Rate Details")

        self.draw_section_title("Source")
        self.draw_key_value_rows(
            [
                ("Title", source.get("title")),
                ("URL", source.get("url")),
                ("Category", source.get("category")),
                ("Retrieved", source.get("retrieved")),
                ("Note", source.get("note")),
            ],
            continuation_title="Source",
        )

        self.draw_section_title("Source Proof")
        proof_rows: list[tuple[str, object]] = []
        if isinstance(saved_files, list) and saved_files:
            for index, item in enumerate(saved_files, start=1):
                if isinstance(item, dict):
                    filename = item.get("filename") or Path(str(item.get("path", ""))).name
                    proof_rows.append((f"Saved source {index}", f"{filename} (retained in this proof packet)"))
                    proof_rows.append((f"SHA-256 {index}", item.get("sha256")))
            proof_rows.append(("Reviewer note", "Provide this PDF together with the saved source proof file(s); local computer paths are not required to verify the source hash."))
        else:
            proof_rows.append(("Source proof", "No local source artifact was saved; see proof limitations."))
        self.draw_key_value_rows(proof_rows, continuation_title="Source Proof")

        if isinstance(limitations, list) and limitations:
            self.draw_section_title("Proof Limitations")
            self.draw_bullets(limitations)

        if isinstance(caveats, list) and caveats:
            self.draw_section_title("Caveats")
            self.draw_bullets(caveats)

        self.draw_footer()
        return self.pages


def pdf_document_bytes(pages: list[list[str]], *, title: str, skill_name: str) -> bytes:
    objects: list[bytes] = []
    page_object_ids: list[int] = []

    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"")  # pages object placeholder
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique >>")

    for page_commands in pages:
        content = "\n".join(page_commands).encode("latin-1", errors="replace")
        content_id = len(objects) + 1
        objects.append(
            b"<< /Length " + str(len(content)).encode("ascii") + b" >>\nstream\n" + content + b"\nendstream"
        )
        page_id = len(objects) + 1
        page_object_ids.append(page_id)
        objects.append(
            (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PDF_PAGE_WIDTH} {PDF_PAGE_HEIGHT}] "
                f"/Resources << /ProcSet [/PDF /Text] /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >> >> "
                f"/Contents {content_id} 0 R >>"
            ).encode("ascii")
        )

    kids = " ".join(f"{page_id} 0 R" for page_id in page_object_ids)
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_object_ids)} >>".encode("ascii")
    info_id = len(objects) + 1
    objects.append(
        (
            f"<< /Title ({escape_pdf_text(title)}) /Creator ({skill_name}) "
            f"/Producer ({skill_name} standard-library PDF renderer) >>"
        ).encode("latin-1", errors="replace")
    )

    output = io.BytesIO()
    output.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for object_id, payload in enumerate(objects, start=1):
        offsets.append(output.tell())
        output.write(f"{object_id} 0 obj\n".encode("ascii"))
        output.write(payload)
        output.write(b"\nendobj\n")

    xref_start = output.tell()
    output.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.write(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R /Info {info_id} 0 R >>\n"
            f"startxref\n{xref_start}\n%%EOF\n"
        ).encode("ascii")
    )
    return output.getvalue()


def render_workpaper_pdf_bytes(workpaper: dict[str, object]) -> bytes:
    renderer = WorkpaperPdfRenderer(workpaper)
    pages = renderer.render()
    presentation = workpaper.get(_PRESENTATION_KEY) or {}
    assert isinstance(presentation, dict)
    document_title = str(presentation.get("document_title", "FX Rate Workpaper"))
    title = f"{workpaper['currency']} {workpaper['year']} {document_title}"
    return pdf_document_bytes(pages, title=title, skill_name=str(workpaper.get("skill", "")))


# --------------------------------------------------------------------------- #
# Markdown + cited-answer helpers.                                             #
# --------------------------------------------------------------------------- #


def render_workpaper_md(workpaper: dict[str, object]) -> str:
    source = workpaper["source"]
    proof = workpaper["proof"]
    assert isinstance(source, dict)
    assert isinstance(proof, dict)
    presentation = workpaper.get(_PRESENTATION_KEY) or {}
    assert isinstance(presentation, dict)
    document_title = str(presentation.get("document_title", "FX Rate Workpaper"))
    rate_phrase = str(presentation.get("rate_phrase", ""))
    extra_rows = list(presentation.get("extra_rows", ()))

    saved_files = proof.get("saved_files", [])
    limitations = proof.get("limitations", [])

    lines = [
        f"# {document_title}",
        "",
        f"Currency: {workpaper['currency']}",
        f"Year: {workpaper['year']}",
    ]
    for label, value in extra_rows:
        lines.append(f"{label}: {value}")
    lines.extend(
        [
            f"Rate: 1 USD = {workpaper['foreign_per_usd']} {workpaper['currency']} {rate_phrase}",
            f"Reciprocal: 1 {workpaper['currency']} = {workpaper['usd_per_foreign']} USD",
            f"Source: {source.get('title')}",
            f"Source URL: {source.get('url')}",
            f"Source category: {source.get('category')}",
            f"Retrieved: {source.get('retrieved')}",
            f"Source note: {source.get('note')}",
            "",
            "## Proof Files",
            f"- Workpaper PDF: {proof.get('workpaper_pdf')}",
        ]
    )

    if saved_files:
        for item in saved_files:
            assert isinstance(item, dict)
            lines.append(f"- {item.get('path')} (sha256: {item.get('sha256')})")
    else:
        lines.append("- No local source artifact was saved; see proof limitations.")

    if limitations:
        lines.extend(["", "## Proof Limitations"])
        for item in limitations:
            lines.append(f"- {item}")

    lines.extend(["", "## Caveats"])
    for caveat in workpaper.get("caveats", []):
        lines.append(f"- {caveat}")
    lines.append("")
    return "\n".join(lines)


def markdown_file_link(label: str, path: object) -> str:
    target = clean_text(str(path))
    safe_label = clean_text(label).replace("[", "\\[").replace("]", "\\]")
    safe_target = target.replace(">", "%3E")
    return f"[{safe_label}](<{safe_target}>)"


def artifact_links(workpaper: dict[str, object]) -> str:
    proof = workpaper["proof"]
    assert isinstance(proof, dict)
    links: list[str] = []
    seen: set[str] = set()

    for key, label in (
        ("workpaper_pdf", "workpaper.pdf"),
        ("workpaper_md", "workpaper.md"),
        ("workpaper_json", "workpaper.json"),
    ):
        path = proof.get(key)
        if path and str(path) not in seen:
            links.append(markdown_file_link(label, path))
            seen.add(str(path))

    saved_files = proof.get("saved_files", [])
    if isinstance(saved_files, list):
        for item in saved_files:
            if not isinstance(item, dict):
                continue
            path = item.get("path")
            if path and str(path) not in seen:
                links.append(markdown_file_link(Path(str(path)).name, path))
                seen.add(str(path))

    return ", ".join(links)


def final_text(workpaper: dict[str, object]) -> str:
    source = workpaper["source"]
    proof = workpaper["proof"]
    assert isinstance(source, dict)
    assert isinstance(proof, dict)
    presentation = workpaper.get(_PRESENTATION_KEY) or {}
    assert isinstance(presentation, dict)
    rate_phrase = str(presentation.get("rate_phrase", ""))
    pdf_path = proof.get("workpaper_pdf")
    proof_link = markdown_file_link("workpaper.pdf", pdf_path) if pdf_path else ""
    return "\n".join(
        [
            f"Rate: 1 USD = {workpaper['foreign_per_usd']} {workpaper['currency']} {rate_phrase}",
            f"Reciprocal: 1 {workpaper['currency']} = {workpaper['usd_per_foreign']} USD",
            f"Source: {source.get('title')}, {source.get('url')}, retrieved {source.get('retrieved')}",
            f"Proof: {proof_link}",
            f"Artifacts: {artifact_links(workpaper)}",
        ]
    )


# --------------------------------------------------------------------------- #
# Build entry point.                                                           #
# --------------------------------------------------------------------------- #


# Top-level keys the kit computes itself; extra_json may add new keys and
# deep-merge into ``source``, but must not overwrite these (doing so could
# clobber the proof block or forge the skill name).
_RESERVED_TOP_KEYS = frozenset(
    {
        "skill",
        "currency",
        "year",
        "rate",
        "rate_direction",
        "foreign_per_usd",
        "usd_per_foreign",
        "proof",
        "caveats",
    }
)


def _validate_extra_json(extra: object) -> None:
    if not isinstance(extra, dict):
        raise RateError("extra_json must be a dict.", 2)
    clobbered = _RESERVED_TOP_KEYS & set(extra)
    if clobbered:
        raise RateError(
            f"extra_json must not overwrite reserved keys: {', '.join(sorted(clobbered))}.", 2
        )
    if "source" in extra and not isinstance(extra["source"], dict):
        raise RateError("extra_json['source'] must be a dict to merge into the source block.", 2)


def _deep_merge(base: dict, extra: dict) -> dict:
    """Overlay ``extra`` onto ``base`` in place, recursing into nested dicts.

    Year-end's ``source.year_end_confirmed`` is nested, so a shallow update
    would clobber the whole ``source`` block. Dict-vs-dict collisions recurse;
    every other collision takes the ``extra`` value.
    """
    for key, value in extra.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value
    return base


def _copy_saved_proofs(folder: Path, saved_proofs: Iterable[Path], *, proof_required: bool) -> list[dict[str, object]]:
    """Copy each proof into the packet folder and record its hashed entry.

    ``proof_required`` determines whether an unusable proof raises ``RateError``
    or is skipped.
    """
    entries: list[dict[str, object]] = []
    for index, original_path in enumerate(saved_proofs, start=1):
        proof_path = original_path
        # is_file() (not exists()) so a directory or broken symlink fails as a
        # clean RateError instead of an IsADirectoryError from copy2/hashing.
        if not proof_path.is_file():
            if proof_required:
                raise RateError(f"Proof file does not exist or is not a regular file: {proof_path}", 2)
            continue
        if proof_path.parent.resolve() != folder.resolve():
            copied_name = f"source-proof-{index}{proof_path.suffix}"
            copied_path = folder / copied_name
            shutil.copy2(proof_path, copied_path)
            proof_path = copied_path
        entries.append(
            {
                "filename": proof_path.name,
                "packet_relative_path": proof_path.name,
                "path": as_abs(proof_path),
                "sha256": sha256_file(proof_path),
            }
        )
    return entries


def build_workpaper(spec: WorkpaperSpec) -> dict[str, object]:
    """Build the proof packet (md + json + pdf + copied/hashed proofs).

    Writes into ``<output_root>/<code>-<year>-<slug(source_title)>/`` and
    returns the workpaper dict (carrying a stripped ``_presentation`` block for
    the cited-answer helpers). Always warns to stderr when replacing an
    existing packet - the hardened behavior both skills now inherit.
    """
    foreign_per_usd, usd_per_foreign = build_rate_values(spec.rate, spec.rate_direction)
    if spec.extra_json:
        _validate_extra_json(spec.extra_json)
    try:
        year = int(spec.year)
    except (TypeError, ValueError) as exc:
        raise RateError(f"Year must be an integer, got {spec.year!r}.", 2) from exc
    source_slug = slugify(spec.source_title)
    # Slug the currency code and use an int year so neither can inject a path
    # separator or traversal sequence into the packet folder.
    folder = Path(spec.output_root) / f"{slugify(spec.currency_code)}-{year}-{source_slug}"
    if (folder / "workpaper.json").exists():
        print(f"note: replacing existing workpaper packet at {folder}", file=sys.stderr)
    folder.mkdir(parents=True, exist_ok=True)

    proof_entries = _copy_saved_proofs(folder, spec.saved_proofs, proof_required=spec.proof_required)
    proof_limitations = list(spec.proof_limitations)
    if spec.proof_required and not proof_entries:
        proof_limitations = proof_limitations + [NO_PROOF_LIMITATION]

    workpaper: dict[str, object] = {
        "skill": spec.skill_name,
        "currency": spec.currency_code,
        "year": year,
        "rate": fmt_decimal(spec.rate),
        "rate_direction": spec.rate_direction,
        "foreign_per_usd": fmt_decimal(foreign_per_usd),
        "usd_per_foreign": fmt_decimal(usd_per_foreign),
        "source": {
            "title": spec.source_title,
            "url": spec.source_url,
            "category": spec.source_category,
            "retrieved": spec.retrieval_date,
            "note": spec.source_note,
        },
        "proof": {
            "workpaper_md": as_abs(folder / "workpaper.md"),
            "workpaper_json": as_abs(folder / "workpaper.json"),
            "workpaper_pdf": as_abs(folder / "workpaper.pdf"),
            "saved_files": proof_entries,
            "limitations": proof_limitations,
        },
        "caveats": list(spec.caveats),
    }

    if spec.extra_json:
        _deep_merge(workpaper, spec.extra_json)

    workpaper[_PRESENTATION_KEY] = {
        "document_title": spec.document_title,
        "document_subtitle": spec.document_subtitle,
        "rate_phrase": spec.rate_phrase,
        "extra_rows": list(spec.extra_rows),
    }

    markdown_text = render_workpaper_md(workpaper)
    (folder / "workpaper.md").parent.mkdir(parents=True, exist_ok=True)
    (folder / "workpaper.md").write_text(markdown_text, encoding="utf-8")

    pdf_path = folder / "workpaper.pdf"
    pdf_path.write_bytes(render_workpaper_pdf_bytes(workpaper))
    proof_block = workpaper["proof"]
    assert isinstance(proof_block, dict)
    proof_block["workpaper_pdf_sha256"] = sha256_file(pdf_path)

    serializable = {key: value for key, value in workpaper.items() if not key.startswith("_")}
    (folder / "workpaper.json").write_text(
        json.dumps(serializable, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return workpaper
